begin;

-- Phase 3 correction: wallets are user-managed payment sources. There is no
-- system default, archive lifecycle, or automatic wallet assignment.
drop trigger if exists auth_user_default_wallet on auth.users;
drop function if exists private.create_default_wallet_for_user();

drop trigger if exists transactions_00_assign_default_wallet
on public.transactions;
drop trigger if exists category_budgets_00_assign_default_wallet
on public.category_budgets;
drop function if exists private.assign_default_wallet();

drop trigger if exists transactions_active_wallet_guard
on public.transactions;
drop trigger if exists category_budgets_active_wallet_guard
on public.category_budgets;
drop function if exists private.guard_active_wallet_write();

drop trigger if exists wallets_default_guard on public.wallets;
drop function if exists private.protect_default_wallet();

-- Remove empty system-created migration wallets. A migration wallet that owns
-- legacy data is retained only to avoid silent data loss; after the columns are
-- dropped it has no special behavior and the user may rename or delete it.
delete from public.wallets as wallet
where wallet.is_default
  and not exists (
    select 1 from public.transactions as transaction_row
    where transaction_row.wallet_id = wallet.id
  )
  and not exists (
    select 1 from public.category_budgets as budget
    where budget.wallet_id = wallet.id
  );

drop index if exists public.wallets_user_default_unique_idx;
drop index if exists public.wallets_user_active_idx;

drop policy if exists "Users can create their own wallets" on public.wallets;
alter table public.wallets
  drop column if exists is_default,
  drop column if exists archived_at;

create index wallets_user_created_idx
on public.wallets (user_id, created_at, id);

create policy "Users can create their own wallets"
on public.wallets for insert to authenticated
with check ((select auth.uid()) = user_id);

comment on table public.wallets is
  'User-created payment sources such as bank accounts, e-wallets, and cash. Wallets classify expenses and do not fetch or represent live balances.';

create function public.get_wallet_deletion_summaries()
returns table (
  wallet_id uuid,
  transaction_count integer,
  budget_count integer,
  receipt_count integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    wallet.id,
    (
      select count(*)::integer
      from public.transactions as transaction_row
      where transaction_row.user_id = wallet.user_id
        and transaction_row.wallet_id = wallet.id
    ),
    (
      select count(*)::integer
      from public.category_budgets as budget
      where budget.user_id = wallet.user_id
        and budget.wallet_id = wallet.id
    ),
    (
      select count(*)::integer
      from public.transactions as transaction_row
      where transaction_row.user_id = wallet.user_id
        and transaction_row.wallet_id = wallet.id
        and transaction_row.receipt_object_key is not null
    )
  from public.wallets as wallet
  where wallet.user_id = auth.uid()
  order by wallet.created_at, wallet.id;
$$;

revoke all on function public.get_wallet_deletion_summaries()
from public, anon;
grant execute on function public.get_wallet_deletion_summaries()
to authenticated;

create function public.delete_wallet_with_data(p_wallet_id uuid)
returns table (
  deleted_wallet_id uuid,
  transaction_count integer,
  budget_count integer,
  receipt_count integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_transaction_count integer;
  v_budget_count integer;
  v_receipt_count integer;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if public.get_account_access_state() <> 'active' then
    raise exception 'active account required' using errcode = '42501';
  end if;
  if not exists (
    select 1 from public.wallets as wallet
    where wallet.id = p_wallet_id and wallet.user_id = v_user_id
  ) then
    raise exception 'wallet not found' using errcode = 'P0002';
  end if;

  select count(*)::integer,
    count(*) filter (where transaction_row.receipt_object_key is not null)::integer
  into v_transaction_count, v_receipt_count
  from public.transactions as transaction_row
  where transaction_row.user_id = v_user_id
    and transaction_row.wallet_id = p_wallet_id;

  select count(*)::integer into v_budget_count
  from public.category_budgets as budget
  where budget.user_id = v_user_id
    and budget.wallet_id = p_wallet_id;

  -- Stored narratives summarize account aggregates. Removing any wallet makes
  -- them stale, so they are cleared and will be regenerated by existing flows.
  delete from public.weekly_insights where user_id = v_user_id;
  delete from public.monthly_insights where user_id = v_user_id;

  delete from public.wallets
  where id = p_wallet_id and user_id = v_user_id;

  return query select
    p_wallet_id,
    v_transaction_count,
    v_budget_count,
    v_receipt_count;
end;
$$;

revoke all on function public.delete_wallet_with_data(uuid)
from public, anon;
grant execute on function public.delete_wallet_with_data(uuid)
to authenticated;

notify pgrst, 'reload schema';
commit;
